apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-harbor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "100g"
spec:
  rules:
  - host: harbor.default.k8s_project.k8s_domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: harbor
            port:
              number: 80
  - host: notary.default.k8s_project.k8s_domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: harbor-release-notary-server
            port:
              number: 4443
  tls:
    - hosts:
        - harbor.default.k8s_project.k8s_domain
        - notary.default.k8s_project.k8s_domain
      secretName: ingress-harbor-tls
