apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      X-Forwarded-Host: nexus.k8s_project.topzone.me;
spec:
#  tls:
#    - hosts:
#        - https-wordpress.topzone8713
#      secretName: default-token-nv5hl
  rules:
#  - host: https-wordpress.topzone8713
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: wordpress
#            port:
#              number: 30085
  - host: ae06c8888b6ff49bb8b181496593edba-196345690.ap-northeast-2.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexus
            port:
              number: 32169
