apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
#    cert-manager.io/cluster-issuer: "letsencrypt-prod"
#    nginx.ingress.kubernetes.io/auth-snippet: |
#      proxy_set_header Host $http_host;
#    nginx.ingress.kubernetes.io/auth-type: basic
#    nginx.ingress.kubernetes.io/auth-secret: basic-auth-grafana
#    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - admin'
spec:
  rules:
#  - host: grafana.k8s_domain
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: prometheus-grafana
#          servicePort: 3000
  - host: grafana.default.k8s_project.k8s_domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 3000
#  tls:
#    - hosts:
##        - grafana.k8s_domain
#        - grafana.default.k8s_project.k8s_domain
#      secretName: ingress-grafana-tls
