
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opentelemetry-collector-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-stz-verify: 'false'
    nginx.ingress.kubernetes.io/stz-redirect: 'false'
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: opentelemetry.topzone.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opentelemetry-collector
            port:
              number: 4318
  tls:
    - hosts:
        - opentelemetry.topzone.me
      secretName: opentelemetry-collector-ingress-tls
