server:
  additionalApplications:
  - name: app-of-app
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/doogee323/demo-app.git
      targetRevision: HEAD
      path: demo-app/argocd
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      #automated:
      #  selfHeal: true
      #  prune: true
